millage_group:
  outputs:
    dev:
      account: ik42880.eu-west-1
      database: "{{env_var('snowflake_database')}}"
      private_key_passphrase: "{{env_var('private_key_passphrase')}}"
      private_key_path: "{{env_var('private_key_path')}}"
      role: 
      schema: "{{env_var('snowflake_schema')}}"
      threads: 1
      type: snowflake
      user: "{{env_var('snowflake_user')}}"
      warehouse: transform_wh
  target: dev
