millage_group:
  outputs:
    dev:
      account: ik42880.eu-west-1
      database: analytics
      private_key_passphrase: "{{env_var('private_key_passphrase')}}"
      private_key_path: "{{env_var('private_key_path')}}"
      role: 
      schema: reports
      threads: 1
      type: snowflake
      user: FIKAYOL
      warehouse: transform_wh
  target: dev
